# Generated by Django 4.2.10 on 2025-03-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_course_enrollment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="enrollment_date",
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-01-01 13:33:36"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-01-01 13:33:36"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
