# Generated by Django 4.2.10 on 2025-03-10 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_enrollment_enrollment_date_course_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="faculty",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="enrolled_at",
        ),
        migrations.AddField(
            model_name="course",
            name="total_assignments",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="course",
            name="total_classes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="attended_classes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="completed_assignments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
