# Generated by Django 4.2.10 on 2025-03-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_course_created_at_remove_course_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
