# Generated by Django 4.2.10 on 2025-03-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="progress",
            field=models.FloatField(default=0.0),
        ),
    ]
